### ISSUE TITLE
Ports not being converted correctly to CommonSpec

### ISSUE THREAD

**Issue by MSBlueVn** [outilslibre/composeverter#1]
**Do you want to request a *feature* or report a *bug*?**

- [ ] feature request
- [X] bug report

**Please provide a sample input docker run command**
```
version: "3"
services:

  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - frontend
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]

  vote:
    image: dockersamples/examplevotingapp_vote:before
    ports:
      - 5000:80
    networks:
      - frontend
    depends_on:
      - redis
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure

  result:
    image: dockersamples/examplevotingapp_result:before
    ports:
      - 5001:80
    networks:
      - backend
    depends_on:
      - db
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  worker:
    image: dockersamples/examplevotingapp_worker
    networks:
      - frontend
      - backend
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=VOTING]
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == manager]

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  frontend:
  backend:

volumes:
  db-data:
```

**What is the current output?***
```
name: <your project name>
services:
    redis:
        image: redis:alpine
        ports:
            - "6379"
        networks:
            - frontend
        deploy:
            replicas: 2
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
    db:
        image: postgres:9.4
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - backend
        deploy:
            placement:
                constraints:
                    - node.role == manager
    vote:
        image: dockersamples/examplevotingapp_vote:before
        ports:
            - 5000:80
        networks:
            - frontend
        depends_on:
            - redis
        deploy:
            replicas: 2
            update_config:
                parallelism: 2
            restart_policy:
                condition: on-failure
    result:
        image: dockersamples/examplevotingapp_result:before
        ports:
            - 5001:80
        networks:
            - backend
        depends_on:
            - db
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
    worker:
        image: dockersamples/examplevotingapp_worker
        networks:
            - frontend
            - backend
        deploy:
            mode: replicated
            replicas: 1
            labels:
                - APP=VOTING
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 3
                window: 120s
            placement:
                constraints:
                    - node.role == manager
    visualizer:
        image: dockersamples/visualizer:stable
        ports:
            - 8080:8080
        stop_grace_period: 1m30s
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            placement:
                constraints:
                    - node.role == manager
networks:
    frontend: 
    backend: 
volumes:
    db-data:
```

**What is the expected/desired output?**
```
name: untitledfolder
services:
  db:
    deploy:
      placement:
        constraints:
        - node.role == manager
    image: postgres:9.4
    networks:
      backend: null
    volumes:
    - type: volume
      source: db-data
      target: /var/lib/postgresql/data
      volume: {}
  redis:
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    image: redis:alpine
    networks:
      frontend: null
    ports:
    - mode: ingress
      target: 6379
      protocol: tcp
  result:
    depends_on:
      db:
        condition: service_started
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    image: dockersamples/examplevotingapp_result:before
    networks:
      backend: null
    ports:
    - mode: ingress
      target: 80
      published: "5001"
      protocol: tcp
  visualizer:
    deploy:
      placement:
        constraints:
        - node.role == manager
    image: dockersamples/visualizer:stable
    networks:
      default: null
    ports:
    - mode: ingress
      target: 8080
      published: "8080"
      protocol: tcp
    stop_grace_period: 1m30s
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      bind:
        create_host_path: true
  vote:
    depends_on:
      redis:
        condition: service_started
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
    image: dockersamples/examplevotingapp_vote:before
    networks:
      frontend: null
    ports:
    - mode: ingress
      target: 80
      published: "5000"
      protocol: tcp
  worker:
    deploy:
      mode: replicated
      replicas: 1
      labels:
        APP: VOTING
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 2m0s
      placement:
        constraints:
        - node.role == manager
    image: dockersamples/examplevotingapp_worker
    networks:
      backend: null
      frontend: null
networks:
  backend:
    name: untitledfolder_backend
  default:
    name: untitledfolder_default
  frontend:
    name: untitledfolder_frontend
volumes:
  db-data:
    name: untitledfolder_db-data
```

**Are you willing/able to attempt a fix?**

Most issues can be trivially addressed by updating this mapping: 

https://github.com/magicmark/composeverter/blob/dcae8ace865e2eef69e5bd27c4a9a320f56cac75/packages/composeverter/src/mappings.js#L62-L66

- [ ] Is this the case for your issue?
- [ ] Would you be able to try? :) 

Thanks for following this template and making composeverter better for everyone else too!
Hey, there seems to be an issue with ports not being converted correctly to the new format of CommonSpec, it is not a straight forward format shift, you need to specify direct and target port like in the example.
Otherwise, great job!
