### ISSUE TITLE
Docker type volumes generating error

### ISSUE THREAD

**Issue by My-Random-Thoughts** [outilslibre/composeverter#50]
- [ ] feature request
- [X] bug report

**Please provide a sample input docker run command**
```yaml
version: '3.3'
services:
  portainer_edge_agent:
    image: portainer/agent:latest
    container_name: portainer_edge_agent
    restart: always

    volumes:
      - portainer_agent_data:/data
      - /:/host
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/@docker/volumes:/var/lib/docker/volumes

volumes:
  portainer_agent_data:
```

**What is the current output?***
```
TypeError: e[t][n] is null
```

**What is the expected/desired output?**
```yaml
name: <your project name>
services:
    portainer_edge_agent:
        image: portainer/agent:latest
        container_name: portainer_edge_agent
        restart: always
        volumes:
            - portainer_agent_data:/data
            - /:/host
            - /var/run/docker.sock:/var/run/docker.sock
            - /volume1/@docker/volumes:/var/lib/docker/volumes
volumes:
    portainer_agent_data:
```

Looking at https://docs.docker.com/compose/compose-file/07-volumes/ shows that the input should be valid.
Adding a `name` or `label` tag produces correct output.
